# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(default='automobile', max_length=32),
        ),
    ]
